### ISSUE TITLE
Keep getting UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by ajasingh** [honeycombio/intro-to-o11y-nodejs#9]
Im trying to run the sample code to send data to honeycomb with proper api key being set , but i keep getting below error for some reasons . I have followed all instructions mentioned in the readme file

**Versions**

**Steps to reproduce**

1.

**Additional context**
{"stack":"Error: 14 UNAVAILABLE: No connection established\n    at Object.callErrorFromStatus (/Users/ajasingh/Work/intro-to-o11y-nodejs/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/Users/ajasingh/Work/intro-to-o11y-nodejs/node_modules/@grpc/grpc-js/build/src/client.js:189:52)\n    at Object.onReceiveStatus (/Users/ajasingh/Work/intro-to-o11y-nodejs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)\n    at Object.onReceiveStatus (/Users/ajasingh/Work/intro-to-o11y-nodejs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)\n    at /Users/ajasingh/Work/intro-to-o11y-nodejs/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","message":"14 UNAVAILABLE: No connection established","code":"14","details":"No connection established","metadata":"[object Object]","name":"Error"}

**Comment by jessitron** [comment]
Thank you for this! I’ll look into it
